[package]

name = "html5ever"
version = "0.14.0"
authors = [ "The html5ever Project Developers" ]
license = "MIT / Apache-2.0"
repository = "https://github.com/servo/html5ever"
description = "High-performance browser-grade HTML5 parser"
documentation = "https://docs.rs/html5ever"
build = "build.rs"

[lib]
name = "html5ever"

# https://github.com/rust-lang/cargo/issues/1512
doctest = false

[[test]]
name = "tree_builder"
harness = false

[[test]]
name = "tokenizer"
harness = false

[[test]]
name = "serializer"

[[bench]]
name = "tokenizer"
harness = false

[features]
unstable = ["tendril/unstable"]
heap_size = ["heapsize", "heapsize_derive", "html5ever-atoms/heap_size"]

[dependencies]
log = "0"
phf = "0.7"
mac = "0"
tendril = "0.2.2"
heapsize = { version = "0.3", optional = true }
heapsize_derive = { version = "0.1", optional = true }
html5ever-atoms = { version = "0.2", path = "./atoms" }

[dev-dependencies]
rustc-serialize = "0.3.15"
rustc-test = "0.1.3"

[build-dependencies]
phf_codegen = "0.7.3"
quote = "0.3.3"
rustc-serialize = "0.3.15"
syn = { version = "0.10", features = ["full", "visit"] }

[profile.dev]
debug = false

[profile.test]
debug = false
